### ISSUE TITLE
"socket hang up" when I do a request to JSON feed

### ISSUE THREAD

**Issue by enzon19** [c3kay/hoyolab-rss-feeds#1]
I don't know if it's your fault, but since last days, I can't make requests to the JSON feed. Every time I try, I receive "socket hang up"/"ECONNRESET"/"ETIMEDOUT"

I'm using node.js with axios.

```js
const axios = require('axios');

simpletest()

function simpletest () {

  console.log(axios.get('https://c3kay.de/hoyolab.json').then(res => console.log(res.data)))

}
```

**Comment by c3kay** [comment]
Hey there! I was receiving a large amount of requests in the last days/weeks and therefore I have blocked them. I think they might be coming from your side since the user-agent matches. Please adjust your request interval to maybe every hour (the feed file is only updated every hour and does not change in the time between) and I will unblock you!

**Comment by enzon19** [comment]
That's true! I was using a converter to XML with a very short interval. Sorry. Now you have the Atom feed, so I already turned off that code.

**Comment by c3kay** [comment]
Alright, you should be unblocked now!
